name: obd2app
description: "A Bimmer Enthusiast's Tool"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path: ^1.8.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1" # Das Tool zur Generierung
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon_raw.png"
  min_sdk_android: 21 # falls nötig

flutter:
  uses-material-design: true

  # Füge diese Zeilen hinzu (achte EXAKT auf die Einrückung von 2 Leerzeichen!)
  assets:
    - assets/mlogo.png
    - assets/models.json
    - assets/dtc_codes.json
